src/nop43/Nop.Plugin.Widgets.LiveChatInc/Controllers/WidgetsLiveChatIncController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Tax;
using Nop.Core.Infrastructure;
using Nop.Plugin.Widgets.LiveChatInc.Models;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Discounts;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Collections.Generic;
using System.Linq;

namespace Nop.Plugin.Widgets.LiveChatInc.Controllers
{
    public class WidgetsLiveChatIncController : BasePluginController
    {
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly ISettingService _settingService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly INotificationService _notificationService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IProductService _productService;

        public WidgetsLiveChatIncController(IWorkContext workContext,
             IStoreContext storeContext,
             ISettingService settingService,
             ILocalizationService localizationService,
            INotificationService notificationService,
             IPermissionService permissionService,
             IShoppingCartService shoppingCartService,
             IProductService productService)
        {
            _workContext = workContext;
            _storeContext = storeContext;
            _settingService = settingService;
            _localizationService = localizationService;
            _permissionService = permissionService;
            _notificationService = notificationService;
            _shoppingCartService = shoppingCartService;
            _productService = productService;
        }

        [Area(AreaNames.Admin)]
        [AuthorizeAdmin]
        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<LiveChatIncSettings>(storeScope);
            var model = new ConfigurationModel
            {
                ActiveStoreScopeConfiguration = storeScope,
                CartUpdateInterval = settings.CartUpdateInterval,
                HideOnMobile = settings.HideOnMobile,
                TrackingCartOptions = new List<SelectListItem>
                {
                    new SelectListItem{ Text="Don't track", Value="0"},
                    new SelectListItem{ Text="Track every 10s", Value="10000"},
                    new SelectListItem{ Text="Track every 30s", Value="30000"},
                },
                License = new ConfigurationModel.LicenseInformation
                {
                    License = settings.License,
                    Login = settings.Login,
                    Version = settings.Version
                }
            };

            if (storeScope > 0)
            {
                model.CartUpdateInterval_OverrideForStore = _settingService.SettingExists(settings, x => x.CartUpdateInterval, storeScope);
                model.HideOnMobile_OverrideForStore = _settingService.SettingExists(settings, x => x.HideOnMobile, storeScope);
                model.License.Login_OverrideForStore = _settingService.SettingExists(settings, x => x.Login, storeScope);
                model.License.License_OverrideForStore = _settingService.SettingExists(settings, x => x.License, storeScope);
                model.License.Version_OverrideForStore = _settingService.SettingExists(settings, x => x.Version, storeScope);
            }

            return View("~/Plugins/Widgets.LiveChatInc/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<LiveChatIncSettings>(storeScope);

            settings.HideOnMobile = model.HideOnMobile;
            settings.CartUpdateInterval = model.CartUpdateInterval;


            _settingService.SaveSettingOverridablePerStore(settings, x => x.HideOnMobile, model.HideOnMobile_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.CartUpdateInterval, model.CartUpdateInterval_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public ActionResult SetLicenseInformation(ConfigurationModel model)
        {
            var license = model.License;

            //load settings for a chosen store scope
            var storeScope = _storeContext.ActiveStoreScopeConfiguration;
            var settings = _settingService.LoadSetting<LiveChatIncSettings>(storeScope);
            settings.Login = license.Login;
            settings.License = license.License;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */

            _settingService.SaveSettingOverridablePerStore(settings, x => x.Login, license.Login_OverrideForStore, storeScope, false);
            _settingService.SaveSettingOverridablePerStore(settings, x => x.License, license.License_OverrideForStore, storeScope, false);

            //now clear settings cache
            _settingService.ClearCache();

            return Json(new { success = true, login = settings.Login, license = settings.License });
        }

        [HttpPost]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public ActionResult ResetSettings()
        {
            //load settings for a chosen store scope
            _settingService.DeleteSetting<LiveChatIncSettings>();
            //now clear settings cache
            _settingService.ClearCache();

            return Json(new { success = true });
        }

        public ActionResult GetCustomerCart()
        {
            var customer = _workContext.CurrentCustomer;
            if (!customer.HasShoppingCartItems)
                return Json(null);

            var cart = _shoppingCartService.GetShoppingCart(customer, shoppingCartType: ShoppingCartType.ShoppingCart, storeId: _storeContext.CurrentStore.Id);
            if (cart.Count == 0)
                return Json(null);

            var productAttributeFormatter = EngineContext.Current.Resolve<IProductAttributeFormatter>();
            var priceFormatter = EngineContext.Current.Resolve<IPriceFormatter>();
            var taxService = EngineContext.Current.Resolve<ITaxService>();
            var taxSettings = EngineContext.Current.Resolve<TaxSettings>();
            var priceCalculationService = EngineContext.Current.Resolve<IPriceCalculationService>();
            var orderTotalCalculationService = EngineContext.Current.Resolve<IOrderTotalCalculationService>();
            var currencyService = EngineContext.Current.Resolve<ICurrencyService>();
            var webHelper = EngineContext.Current.Resolve<IWebHelper>();


            //subtotal
            decimal orderSubTotalDiscountAmountBase;
            decimal subTotalWithoutDiscountBase;
            decimal subTotalWithDiscountBase;

            List<Core.Domain.Discounts.Discount> orderSubTotalAppliedDiscounts;
            var subTotalIncludingTax = _workContext.TaxDisplayType == TaxDisplayType.IncludingTax && !taxSettings.ForceTaxExclusionFromOrderSubtotal;
            orderTotalCalculationService.GetShoppingCartSubTotal(cart, subTotalIncludingTax,
                out orderSubTotalDiscountAmountBase, out orderSubTotalAppliedDiscounts,
                out subTotalWithoutDiscountBase, out subTotalWithDiscountBase);
            decimal subtotalBase = subTotalWithoutDiscountBase;
            decimal subtotal = currencyService.ConvertFromPrimaryStoreCurrency(subtotalBase, _workContext.WorkingCurrency);


            var data = new
            {
                subtotal = priceFormatter.FormatPrice(subtotal, false, _workContext.WorkingCurrency, _workContext.WorkingLanguage, subTotalIncludingTax),
                products = cart.Select(sci =>
                {
                    var product = _productService.GetProductById(sci.ProductId);

                    return new
                    {
                        Quantity = sci.Quantity,
                        ProductName = _localizationService.GetLocalized(product, x => x.Name),
                        Link = webHelper.GetStoreLocation() + Url.Action("ProductDetails", "Product", new { productId = sci.ProductId })
                    };
                }).ToList()
            };

            return Json(data);
        }
    }
}

src/nop43/Nop.Plugin.Widgets.LiveChatInc/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
    Html.AddCssFileParts("~/Plugins/Widgets.LiveChatInc/Content/css/admin.css");
}
@model Nop.Plugin.Widgets.LiveChatInc.Models.ConfigurationModel


@await Component.InvokeAsync("StoreScopeConfiguration")


<script type="text/javascript">
    function showAlert(text_to_put_in_the_box, alert) {
        var alertBox = $('<div class="alert ' + (alert || false ? '  alert-danger' : ' alert-success') + ' alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><span></span></div>');

        alertBox.find('span').text(text_to_put_in_the_box);
        alertBox.prependTo('.wrapper>.content-wrapper');

		setTimeout(function () {
            alertBox.addClass("fadeout");
		},5000);

		setTimeout(function () {
            alertBox.remove();
		},5000);
	}

	function addHandlerToRadioCart(radios, i) {
		radios[i].addEventListener("click", function() {
			if(radios[i].value==="0"){
				document.getElementById("cart_radios").style.display = "none";
			}else if(radios[i].value === "on") {
				document.getElementById("cart_radios").style.display = "block";
			}
		});
	}

    $(document).ready(function () {
		var login_with_livechat = document.getElementById('login-with-livechat');

		var sendMessage = function(msg) {
			login_with_livechat.contentWindow.postMessage(msg, '*');
		};

		var logoutLiveChat = function() {
			sendMessage('logout');
		};

        function receiveMessage(event) {
            if (!event.data)
                return;

			var livechatMessage = JSON.parse(event.data);

			if (livechatMessage.type === 'logged-in' && livechatMessage.eventTrigger === 'click') {
				$('iframe#login-with-livechat').addClass('hidden');
                $('.progress-button').removeClass('hidden');
                setTimeout(function () {
                    $('#@Html.IdFor(model => model.License.Login)').val(livechatMessage.email);
                    $('#@Html.IdFor(model => model.License.License)').val(livechatMessage.license);

                    var form = $('#licenseInformationForm').serialize();

					$.ajax({
						type: 'POST',
						url: '@Url.Action("SetLicenseInformation","WidgetsLiveChatInc")',
                        data: form,
					})
                    .done(function(data) {
                        showAlert('@T("Plugins.Widgets.LiveChatInc.SuccessfullyAdded")');

						$('#after_login_bar').removeClass("hidden");
						$('#before_login_bar').addClass("hidden");
						$('iframe#login-with-livechat').removeClass('hidden');
						$('.progress-button').addClass('hidden');
						$('#login_email').text(livechatMessage.email);
					})
					.fail(function(data) {
						document.getElementsByClassName('alert-success')[0].style.display = "block";
					});
				},1500);
			}
		}

		window.addEventListener("message", receiveMessage, false);

		var livechatLogin = "@Model.License.Login";

		if(livechatLogin === "" || livechatLogin === null) {
			document.getElementById('login-with-livechat').classList.remove("hidden");
			document.getElementById("login_form").classList.remove("hidden");
			document.getElementById("after_login_bar").classList.add("hidden");
			document.getElementById("before_login_bar").classList.remove("hidden");
			} else {
			document.getElementById('login-with-livechat').classList.add("hidden");
			document.getElementById("login_form").classList.add("hidden");
			document.getElementById("after_login_bar").classList.remove("hidden");
			document.getElementById("before_login_bar").classList.add("hidden");
        }

        $("input[name='delete_settings']").on('click', function (e) {
            e.preventDefault();

            $('#@Html.IdFor(model => model.License.Login)').val('');
            $('#@Html.IdFor(model => model.License.License)').val('');
            $('#@Html.IdFor(model => model.CartUpdateInterval)').val("0");
            $('#@Html.IdFor(model => model.HideOnMobile)').prop("checked",false);

            var formEl = $(this).parents('form');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ResetSettings","WidgetsLiveChatInc")',
                data: formEl.serialize(),
            }).done(function (data) {
                    if (data.success === true) {
                        $('#before_login_bar').removeClass("hidden");
                        $('#login-with-livechat').removeClass("hidden");
                        $('#radios').removeClass("hidden");
                        $('#login_form').removeClass("hidden");
                        $('#after_login_bar').addClass("hidden");
                        showAlert('@T("Plugins.Widgets.LiveChatInc.SettingsReset")');
                        logoutLiveChat();


                    }
                });
        });
	});
</script>


<form asp-controller="WidgetsLiveChatInc" asp-action="SetLicenseInformation" method="post" id="licenseInformationForm">
    @Html.HiddenFor(model => model.License.Login)
    @Html.HiddenFor(model => model.License.License)
    @Html.HiddenFor(model => model.License.Version)

    <div class="panel-group @Html.Raw(!string.IsNullOrEmpty(Model.License.Login)?"hidden":string.Empty)" id="before_login_bar">
        <div class="panel panel-default">
            <div class="panel-body" id="main-itegration-container">
                <div id="login-container" class="col-md-6">
                     <img class="livechat_logo2" alt="LiveChat logo" src="@Url.Content("~/Plugins/Widgets.LiveChatInc/Content/img/livechat-nopcommerce.png")"/>
                    <div id="login_form">
                        <div class="progress-button hidden">
                            @T("Plugins.Widgets.LiveChatInc.Saving")
                        </div>
                        <div>
                            <iframe id="login-with-livechat" src="https://addons.livechatinc.com/sign-in-with-livechat" scrolling="no"> </iframe>
                        </div>
                    </div>
                    <div class="text-center padding-5">@T("Plugins.Widgets.LiveChatInc.Or")</div>
                    <div id="livechat_link" class="text-center">
                        <a href="https://my.livechatinc.com/signup?utm_source=nopcommerce.com&utm_medium=integration&utm_campaign=nopcommerce_integration" target="_blank">@T("Plugins.Widgets.LiveChatInc.CreateAccount")</a>
                    </div>
                </div>
                <div class="livechat_screenshot_container col-md-6">
                    <img class="livechat_screenshot" src="@Url.Content("~/Plugins/Widgets.LiveChatInc/Content/img/livechat-app.png")" alt="livechat app" />
                    <p class="text-center">
                        <a href="https://my.livechatinc.com?utm_source=nopcommerce.com&utm_medium=integration&utm_campaign=nopcommerce_integration" target="_blank">
                            @T("Plugins.Widgets.LiveChatInc.UseOurWebApp")
                        </a> @T("Plugins.Widgets.LiveChatInc.OrCheckOutApps") <a href="https://www.livechatinc.com/applications/?utm_source=nopcommerce.com&utm_medium=integration&utm_campaign=nopcommerce_integration" target="_blank">@T("Plugins.Widgets.LiveChatInc.DesktopOrMobile")</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</form>

<form asp-controller="WidgetsLiveChatInc" asp-action="Configure" method="post">
    <div class="panel-group @Html.Raw(string.IsNullOrEmpty(Model.License.Login)?"hidden":string.Empty)" id="after_login_bar">
        <div class="panel panel-default">
            <div class="panel-body" id="main-itegration-container">
                <div id="controls-container" class="col-sm-6">
                    <div class="form-group" id="livechat-text-status-container">
                        <span id="livechat-text-status">@T("Plugins.Widgets.LiveChatInc.CurrentlyUsedAccount") <span id="login_email">@Model.License.Login</span> @T("Plugins.Widgets.LiveChatInc.LiveChatAccount")</span>
                    </div>
                   
                    <div id="cart-interval-form" class="form-group">
                        <nop-override-store-checkbox asp-for="CartUpdateInterval_OverrideForStore" asp-input="CartUpdateInterval" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="CartUpdateInterval" />
                        <nop-select asp-for="CartUpdateInterval" asp-items="Model.TrackingCartOptions" />
                        <span asp-validation-for="CartUpdateInterval"></span>
                    </div>
            
                    <div class="form-group">
                        <nop-override-store-checkbox asp-for="HideOnMobile_OverrideForStore" asp-input="HideOnMobile" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="HideOnMobile" />
                        <nop-editor asp-for="HideOnMobile" />
                        <span asp-validation-for="HideOnMobile"></span>
                    </div>
                    
                    
                    <div id="reset_settings">
                        <div class="form-group">
                            <label id="reset_settings_label">
                                @T("Plugins.Widgets.LiveChatInc.ChangeAccount") <span>
                                <input type="submit" name="delete_settings" value="@T("Plugins.Widgets.LiveChatInc.ResetSettings")" />
                            </span>
                            </label>
                        </div>
                    </div> 
                </div>
                <div class="livechat_screenshot_container col-sm-6">
                    <div class="form-wrapper">
                        <img class="livechat_screenshot second-screen" src="@Url.Content("~/Plugins/Widgets.LiveChatInc/Content/img/livechat-app.png")" alt="livechat app" />
                        <p class="text-center">
                            <a href="https://my.livechatinc.com?utm_source=nopcommerce.com&utm_medium=integration&utm_campaign=nopcommerce_integration" target="_blank">
                                @T("Plugins.Widgets.LiveChatInc.UseOurWebApp")
                            </a> @T("Plugins.Widgets.LiveChatInc.OrCheckOutApps") <a href="https://www.livechatinc.com/applications/?utm_source=nopcommerce.com&utm_medium=integration&utm_campaign=nopcommerce_integration" target="_blank">@T("Plugins.Widgets.LiveChatInc.DesktopOrMobile")</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        &nbsp;
                    </div>
                    <div class="col-md-9">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>